"""Natural-language assistant route.

The assistant is DETERMINISTIC: every number it returns is read from the computed
risk model (see engine/nlq.py). No LLM is permitted to invent financial figures.
"""
from __future__ import annotations
from fastapi import APIRouter, Depends

from .. import schemas
from ..database import get_db
from ..deps import (get_current_user, current_org, get_result,
                    get_recommendations, get_frameworks)
from ..engine import nlq

router = APIRouter(prefix="/api/assistant", tags=["assistant"])

SUGGESTIONS = [
    "What is our overall risk score?",
    "What is the expected annual loss?",
    "What is our Value-at-Risk?",
    "What are the top risk contributors?",
    "Which controls are weakest?",
    "Which assets carry the most risk?",
    "Show risk by business unit",
    "What should we fix first?",
    "How should I spend a budget of ₹2 crore?",
    "How is our NIST CSF coverage?",
]


@router.post("/query")
def query(body: schemas.AssistantRequest, db=Depends(get_db),
          user=Depends(get_current_user), org_id: int = Depends(current_org)):
    result = get_result(db, org_id)
    recommendations = get_recommendations(db, org_id)
    frameworks = get_frameworks(db, org_id)
    answer = nlq.answer(body.question, result, recommendations, frameworks)
    answer["question"] = body.question
    return answer


@router.get("/suggestions")
def suggestions(user=Depends(get_current_user)):
    return {"suggestions": SUGGESTIONS,
            "note": "Answers are computed deterministically from the risk model; "
                    "figures are never generated by a language model."}
